# Generated by Django 3.0.7 on 2024-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('adresse', models.CharField(max_length=500)),
                ('nom_entreprise', models.CharField(max_length=300)),
                ('salaire', models.CharField(max_length=300)),
                ('contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD 6 mois', 'CDD 6 mois'), ('CDD 12 mois', 'CDD 12 mois'), ('CDD 18 mois', 'CDD 18 mois'), ('Stage', 'Stage'), ('Stage 6 mois', 'Stage 6 mois'), ('Alternance', 'Alternance')], max_length=300)),
                ('date', models.DateField()),
                ('short_description', models.CharField(max_length=150)),
                ('long_description', models.TextField()),
            ],
            options={
                'db_table': 'Annonces',
            },
        ),
        migrations.CreateModel(
            name='Candidatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Candidatures',
            },
        ),
    ]
