# Generated by Django 3.0.7 on 2024-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce_id', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=300)),
                ('salaire', models.CharField(max_length=300)),
                ('contrat', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Annonces',
            },
        ),
    ]
