# Generated by Django 3.0.7 on 2024-10-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobfinder_app', '0001_initial'),
        ('jobfinder_compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatures',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobfinder_compte.Particuliers'),
        ),
        migrations.AddField(
            model_name='annonces',
            name='candidature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobfinder_app.Candidatures'),
        ),
    ]
