# Generated by Django 3.0.7 on 2024-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='annonce_id',
        ),
        migrations.AddField(
            model_name='annonces',
            name='nom_entreprise',
            field=models.CharField(default='1', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonces',
            name='contrat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='long_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
