# Generated by Django 4.2 on 2024-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
