# Generated by Django 3.0.7 on 2024-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Candidatures',
            },
        ),
    ]
