# Generated by Django 3.0.7 on 2024-10-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0002_auto_20241016_1338'),
        ('jobfinder_app', '0002_auto_20241016_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='candidature',
        ),
        migrations.AddField(
            model_name='annonces',
            name='entreprise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobfinder_compte.Entreprises'),
        ),
        migrations.AddField(
            model_name='candidatures',
            name='annonce',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobfinder_app.Annonces'),
        ),
    ]
