# Generated by Django 3.0.7 on 2024-10-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0002_alter_annonces_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('pageweb', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('taille', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Entreprises',
            },
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='annonce_id',
        ),
        migrations.AlterField(
            model_name='annonces',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
