# Generated by Django 4.2 on 2024-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0002_auto_20241011_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD 6 mois', 'CDD 6 mois'), ('CDD 12 mois', 'CDD 12 mois'), ('CDD 18 mois', 'CDD 18 mois'), ('Stage', 'Stage'), ('Stage 6 mois', 'Stage 6 mois'), ('Alternance', 'Alternance')], max_length=300),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
