# Generated by Django 3.0.7 on 2024-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0003_auto_20241013_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='adresse',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='short_description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='titre',
            field=models.CharField(max_length=400),
        ),
    ]
