# Generated by Django 3.0.7 on 2024-10-17 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobfinder_app', '0004_auto_20241016_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatures',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
