# Generated by Django 3.0.7 on 2024-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_app', '0006_auto_20241017_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
