# Generated by Django 4.2 on 2024-10-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
