# Generated by Django 3.0.7 on 2024-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=300)),
                ('mdp', models.TextField()),
            ],
            options={
                'db_table': 'Utilisateur',
            },
        ),
    ]
