# Generated by Django 3.0.7 on 2024-10-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='Utilisateurs',
        ),
        migrations.AlterModelTable(
            name='utilisateurs',
            table='Utilisateurs',
        ),
    ]
