# Generated by Django 4.2 on 2024-10-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mdp',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='email',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
