# Generated by Django 3.0.7 on 2024-10-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprises',
            name='annonce',
        ),
        migrations.RemoveField(
            model_name='particuliers',
            name='candidature',
        ),
    ]
