# Generated by Django 3.0.7 on 2024-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0003_entreprises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprises',
            name='taille',
            field=models.CharField(choices=[('0-10', '0-10'), ('10-250', '10-250'), ('250-5000', '250-5000'), ('+5000', '+5000')], max_length=100),
        ),
    ]
