# Generated by Django 3.0.7 on 2024-10-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0004_auto_20241014_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprises',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
