# Generated by Django 3.0.7 on 2024-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0005_entreprises_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprises',
            name='mdp',
            field=models.TextField(),
        ),
    ]
