# Generated by Django 3.0.7 on 2024-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0006_auto_20241014_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprises',
            name='adresse',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entreprises',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entreprises',
            name='nom_entreprise',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entreprises',
            name='pageweb',
            field=models.CharField(max_length=500),
        ),
    ]
