# Generated by Django 3.0.7 on 2024-10-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0007_auto_20241014_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='mdp',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='email',
            new_name='username',
        ),
    ]
