# Generated by Django 3.0.7 on 2024-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0008_auto_20241014_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
