# Generated by Django 3.0.7 on 2024-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0009_auto_20241014_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprises',
            old_name='mdp',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='entreprises',
            name='email',
        ),
        migrations.AddField(
            model_name='entreprises',
            name='username',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
