# Generated by Django 3.0.7 on 2024-10-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder_compte', '0008_auto_20241014_1319'),
        ('jobfinder_compte', '0010_auto_20241014_1303'),
    ]

    operations = [
    ]
